# Spring properties
spring:
  application:
    name: business-service
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      topic: logs
  mail:
    host: smtp.gmail.com
    port: 587
    username: atmosferpoc@gmail.com
    password: fvlugmakqudtjbds
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# HTTP Server
server:
  port: 9000   # HTTP (Tomcat) port

redis:
  host: 18.157.161.104
  port: 6379

jwt:
  secret: atmosfer-poc

base:
  url: http://localhost:5173