# Spring properties
spring:
  application:
    name: business-service
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      topic: logs

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# HTTP Server
server:
  port: 9000   # HTTP (Tomcat) port

redis:
  host: 18.157.161.104
  port: 6379