# Spring properties
spring:
  application:
    name: log-service
  data:
    mongodb:
      uri: mongodb://mongoDbUser:mongoDbUser@18.157.161.104:27017
      database: logs
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      topic: logs
      groupId: service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# HTTP Server
server:
  port: 9003   # HTTP (Tomcat) port