# Spring properties
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      topic: logs
  mail:
    host: smtp.gmail.com
    port: 587
    username: atmosferpoc@gmail.com
    password: fvlugmakqudtjbds
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# HTTP Server
server:
  port: 9001   # HTTP (Tomcat) port

ldap:
  url: ldap://18.157.161.104:389
  partitionSuffix: dc=atmosfer,dc=local
  principal: cn=admin,dc=atmosfer,dc=local
  password: ldapadmin

jwt:
  secret: atmosfer-poc

base:
  url: http://localhost:9001